on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: curl
      uses: wei/curl@v1
      with:
        args: --upload-file mapScripts/bicycleAmenities.geojson https://overpass-api.de/api/interpreter?data=%5Bout%3Ajson%5D%3B%0Anode%0A%20%20%5Bamenity%3Dbicycle_repair_station%5D%0A%20%20%2857.05%2C%20-2.28%2C%2057.23%2C%20-1.95%29%3B%0Aout%3B%0Anode%0A%20%20%5Bamenity%3Dbicycle_parking%5D%0A%20%20%2857.05%2C%20-2.28%2C%2057.23%2C%20-1.95%29%3B%0Aout%3B%0Anode%0A%20%20%5Bbarrier%3Dcycle_barrier%5D%0A%20%20%2857.05%2C%20-2.28%2C%2057.23%2C%20-1.95%29%3B%0Aout%3B%0Anode%0A%20%20%5Bshop%3Dbicycle_shop%5D%0A%20%20%2857.05%2C%20-2.28%2C%2057.23%2C%20-1.95%29%3B%0Aout%3B